### ISSUE TITLE
Editor markdown does not work correctly

### ISSUE THREAD

**Issue by dmbdesignpdx** [contentful/field-editors#1016]
Hello, there is some kind of bug preventing a user from using the markdown editor as expected (compared to the one in the builtin entry editor).

## How it's implemented

Via `@contentful/create-contentful-app` using the `@contentful/app-sdk`:

```jsx
<FieldWrapper
  sdk={sdkRef}
  name={label}
>
  <Field
    sdk={sdkRef}
    widgetId={widget}
  />
</FieldWrapper>
```

## Expected behavior

Builtin entry editor:

https://user-images.githubusercontent.com/5041305/153087205-861baae1-8bbc-4763-879d-f1684939d58c.mov

## Actual behavior

`FieldWrapper` with `Field`

https://user-images.githubusercontent.com/5041305/153087335-a31ec048-4b39-44ca-85a5-9a99943edb68.mov

### Versions

- `@contentful/default-field-editors`:  **1.1.2**
  - `@contentful/field-editor-markdown`: **1.1.1**
- `@contentful/app-scripts`: **0.14.114**
- `@contentful/app-sdk`: **4.3.1**
- `npm`: **8.1.2**
- `node`: **16.13.1**

Please let me know if there is anything else I need to provide. Thank you.

**Comment by jjagutzke** [comment]
Any update here? I'm experiencing the same problem...

**Comment by dmbdesignpdx** [comment]
this behavior still persists when creating a brand new contentful app via `@contentful/create-contentful-app@latest`.

updated versions:
- `@contentful/default-field-editors`: **1.1.16**
- `@contentful/app-scripts`: **1.1.2**
- `@contentful/app-sdk`: **4.4.0**
- `node`: **16.15.0**
- `npm`: **8.9.0**

**Comment by dmbdesignpdx** [comment]
?

**Comment by filipjovasevic996** [comment]
I've encountered same problem today

**Comment by filipjovasevic996** [comment]
> I've encountered same problem today

I've resolved this problem by importing `import 'codemirror/lib/codemirror.css'`. Unfortunately, now i have other issue which is exactly the same like this one https://github.com/contentful/field-editors/issues/1383

**Comment by YvesRijckaert** [comment]
We just released a fix for this issue with @contentful/field-editor-markdown@1.5.3
