### ISSUE TITLE
RichText editor is missing the table option

### ISSUE THREAD

**Issue by drewfitz10** [contentful/field-editors#1144]
The RichText editor on the Contentful site now has the `table` option added to the toolbar. I don't see it in the code here or any APIs to be able to add it ourselves. Are their plans to add it to this package?

**Comment by z0al** [comment]
Hey there. The code is available under the [next](https://github.com/contentful/field-editors/tree/next/packages/rich-text) branch. We plan to merge with master in a few weeks. It will be released as v2.0.0. While there are no breaking changes in terms of the public package API bringing Tables involved a full rewrite of the package using the latest Slate version.

**Comment by RichieRunner** [comment]
Has this been merged? The Readme does not list table as an option.
