### ISSUE TITLE
p-queue is used in default-field-editor but not installed as a dependency

### ISSUE THREAD

**Issue by JacobSoderblom** [contentful/field-editors#1218]
Getting problems when building my custom editor using the default-field-editor package, see below.

```
Error: [vite]: Rollup failed to resolve import "p-queue" from "../../node_modules/.pnpm/@contentful+field-editor-reference@5.0.0_s6jjvkeghnc4oqfctabuqrxqee/node_modules/@contentful/field-editor-reference/dist/field-editor-reference.esm.js".
```

Please solve this by installing the dependency p-queue as a dependency or as a peer-dependency.

**Comment by Rowadz** [comment]
This was fixed after https://github.com/contentful/field-editors/commit/85763896092414acce8e3e2f81f375dcf983b49f
