### ISSUE TITLE
Issue with react-sortable-hoc and React 18

### ISSUE THREAD

**Issue by maroun9t** [contentful/field-editors#1345]
I recently ran into an issue on an app using React 18 and the @contentful/field-editor-reference package.

The re-ordering of references inside the [MultipleReferenceEditor](https://github.com/contentful/field-editors/blob/b7cd2dbf16d2d8a638db6817cfda5e50ce65dc88/packages/reference/src/common/MultipleReferenceEditor.tsx) component seems to break at random. 

Running the app in React 17 mode, using the [legacy client rendering APIs](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis) seems to fix the issue.

MultipleReferenceEditor relies on [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc) library which doesn't support React 18 and is no longer actively maintained. Are there any plans to migrate to a different drag-and-drop/sorting React library?

**Comment by jonmckee** [comment]
I have this question also.

**Comment by YvesRijckaert** [comment]
@maroun9t Hi and thank you for your request, we have this in our backlog and will look at replacing react-sortable-hoc soon.
