### ISSUE TITLE
Default field editors do not look like the latest Contentful UI

### ISSUE THREAD

**Issue by j-quelly** [contentful/field-editors#1465]
Is there any plans to make the default field look like the latest design in Contentful?

**Comment by z0al** [comment]
Hey @j-quelly, could you elaborate on what's missing/different?

**Comment by vipulchadda** [comment]
One of the difference between the default field editors and the fields in the web app is the colour for the field title.

**Contentful web app**
![Screenshot 2024-01-16 at 12 00 57 PM](https://github.com/contentful/field-editors/assets/31496466/73ebdba6-b1f6-4f4e-9380-b4691c75e1b0)
**Custom app with Default field editor**
![Screenshot 2024-01-16 at 12 01 02 PM](https://github.com/contentful/field-editors/assets/31496466/587b0be2-2ebe-4a2a-b403-624d732decf0)
