### ISSUE TITLE
Attempted import error: 'File' is not exported from './typesEntity'.

### ISSUE THREAD

**Issue by njnygaard** [contentful/field-editors#1467]
```
/common/temp/node_modules/.pnpm/@contentful+field-editor-shared@1.3.1_a7b56dbae31d33320d1487cc61517191/node_modules/@contentful/field-editor-shared/dist/esm/index.js
Attempted import error: 'File' is not exported from './typesEntity'.
```
We're having an issue with this error in a Rush project.
I'm not sure what context to provide but we didn't have the issue with `@contentful/field-editor-shared/1.1.8`.
Any advice is appreciated.

**Comment by 2wce** [comment]
shouldn't be an issue on the latest version
