### ISSUE TITLE
Could not resolve dependency: peer @babel/core@"^7.11.0" from @babel/eslint-parser@7.23.3

### ISSUE THREAD

**Issue by Wounded-Knee** [contentful/field-editors#1644]
Upon executing `npm install` against a fresh clone of this repository, NPM fails with the following output:

> # npm resolution error report
> 
> While resolving: @contentful/field-editors@1.0.0
> Found: @babel/core@7.9.6
> node_modules/@babel/core
>   dev @babel/core@"7.9.6" from the root project
> 
> Could not resolve dependency:
> peer @babel/core@"^7.11.0" from @babel/eslint-parser@7.23.3
> node_modules/@babel/eslint-parser
>   dev @babel/eslint-parser@"7.23.3" from the root project
> 
> Fix the upstream dependency conflict, or retry
> this command with --force or --legacy-peer-deps
> to accept an incorrect (and potentially broken) dependency resolution.

**Comment by 2wce** [comment]
hi @Wounded-Knee thank you for bringing this up, the repository has a yarn.lock file so we recommend running `yarn install` instead of `npm install` this should run the install command successfully
