### ISSUE TITLE
Links to PlateJS in Rich Text field README lead to phishing scam

### ISSUE THREAD

**Issue by daniel-keller** [contentful/field-editors#1698]
Links in the Rich Text [README](https://github.com/contentful/field-editors/tree/master/packages/rich-text) currently redirect to a site attempting a phishing scam.
Presumably the links should lead to https://platejs.org/.

**Comment by chrishelgert** [comment]
Hey 👋 
Thanks for reporting, we gonna adjust the URL's soon
