### ISSUE TITLE
Snyk XSS plate-media@23.7.0 

### ISSUE THREAD

**Issue by Muskos** [contentful/field-editors#1700]
Snyk found a Cross-site Scripting (XSS) with [High Severity].
<img width="807" alt="Screenshot 2024-07-18 at 22 26 03" src="https://github.com/user-attachments/assets/13b69b20-9af5-4c1a-8379-79d00ea2da54">
To handle this issue I can override dependencies. But it will be better to fix it in the origin package.
I tried to create a PR with fixes, but I can't resolve types in `src/test-utils/createEditor.ts`. Could someone help to update the dependencies?

**Comment by 2wce** [comment]
issue was fixed in #1756
