### ISSUE TITLE
Asset options are going out of view port in SingleMediaEditor

### ISSUE THREAD

**Issue by stefanjudis** [contentful/field-editors#188]
I used the `SingleMediaEditor` in an App field extension and it works great. One thing I noticed is that the edit options (`edit` / `remove`) behind the three dots are going out of the iframe viewport.

It would be great to implement the behavior of the `SingleEntryReferenceEditor`. This editor seems to take of that by placing the tooltip in the visible area. :) Thanks.

![Screenshot 2020-05-22 at 10 49 53](https://user-images.githubusercontent.com/962099/82650038-62451a00-9c1a-11ea-9087-d88b123d3007.png)

☝️ Example shows that the reference editor is 100% functional, whereas the asset editor places the tool tip out of reach.

**Comment by suevalov** [comment]
Thanks for the question @stefanjudis. This issue highlights the problem in Forma36 https://github.com/contentful/forma-36/issues/361 that we need to solve to make all dropdown elements position properly.

As a temporary workaround, I would propose forcing dropdown always to open to the bottom.

**Comment by giotiskl** [comment]
#462 introduces using popper for the dropdown, it should fix this issue
