### ISSUE TITLE
How to keep source format after pasting to Rich text editor?

### ISSUE THREAD

**Issue by manhthepixta** [contentful/field-editors#265]
Something like this. The html tags are **preserved** after pasting

https://youtu.be/mzf5DsJ6Ayg

**Comment by suevalov** [comment]
Hi @manhthepixta!

Rich text field editor uses Slate.js under the hood. According to Slate documentation, there's an option to implement formatted paste: https://www.slatejs.org/examples/paste-html

We don't plan to implement it at the moment but feel free to fork the current repository and add this functionality.

**Comment by diegoaguilar** [comment]
@suevalov isn't the current Contentful web app using formatted paste indeed?
