### ISSUE TITLE
Provide a wrapper around all field editors

### ISSUE THREAD

**Issue by stefanjudis** [contentful/field-editors#282]
Hello everybody,

when building complex apps that for example are running in the entry location it would be great to have a component available that wraps all Contentful editors. The idea would be to have this wrapper component which renders the "default Contentful experience" depending on its field type.

A component could look like the component used in [the grouping fields example](https://github.com/contentful/field-editors/blob/b0ea0c5a17e7318c12a0654d6fbf681320ca3698/extensions/entry-extension-collapsible/src/Field.tsx).

```
<Field key={k.id} field={fields[k.id]} locales={locales} />
```

Having something like this available could speed up building complex apps, because developers wouldn't have to think about how to render the default Contentful experience for an entry field. Additionally, it would lead to cleaner apps because developers don't have to write this big `switch` themselves anymore. :)

**Comment by suevalov** [comment]
Thanks for reporting @stefanjudis! We'll definitely be looking into this in the upcoming future. Stay tuned!

**Comment by djagya** [comment]
Hi @stefanjudis. We just released a new package `@contentful/default-field-editors` which exposes two React components:

- `Field` to render a field editor
- `FieldWrapper` to render label, validation errors and help text around this field editor

You can see how we use it in the same [grouping fields example](https://github.com/contentful/field-editors/blob/master/extensions/entry-extension-collapsible/src/Field.tsx#L44) you linked before.

**Comment by stefanjudis** [comment]
That's awesome! Thank you! :)

**Comment by stefanjudis** [comment]
@djagya Is it included in the docs, too? https://contentful-field-editors.netlify.app/
