### ISSUE TITLE
Allow renderProps for media editors

### ISSUE THREAD

**Issue by stefanjudis** [contentful/field-editors#319]
This is a follow up to #283. It'd be great to have renderProps for the media ref editors, too. 🙈

**Comment by suevalov** [comment]
@DanweDE @djagya is it possible with the latest changes in field-editors-reference, isn't it?

**Comment by djagya** [comment]
Not possible yet, I will work on bringing it to the media ref editors.

**Comment by djagya** [comment]
This PR https://github.com/contentful/field-editors/pull/469 adds the support for custom cards in media editors.
