### ISSUE TITLE
Using editors in standalone app

### ISSUE THREAD

**Issue by ryanwalters** [contentful/field-editors#452]
Hi there, this is more of a question than an issue. Apologies if this is a dumb question!

Is it possible to use these editors as components in a web app outside of the Contentful UI? For example, we have an internal web app that we would like to use to manage Contentful content outside of the Contentful dashboard.

I tried using an example similar to the following, but it didn't work, the callback from the `init` function never gets called:
```js
import { init } from 'contentful-ui-extensions-sdk';
import { RichTextEditor } from '@contentful/field-editor-rich-text';

const OurPage = () => {
  const [sdk, setSdk] = useState();

  useEffect(() => {
    // The callback from `init` never gets called

    init((initSdk) => setSdk(initSdk));
  }, []);

  return sdk && <RichTextEditor sdk={sdk} />;
};
```

**Comment by suevalov** [comment]
Hi @ryanwalters!

Thanks for asking the question. All field editors are designed to work only inside Contentful Web App or Contentful UI Extensions / Contentful Apps.

Using them in your custom standalone app is not possible unless you will be able to implement `sdk` instance by your own (including all data and all methods).

**Comment by ashakeel-acro** [comment]
@ryanwalters Did you ever find a solution for this?
