### ISSUE TITLE
rich-text: Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by voronianski** [contentful/field-editors#454]
`setState` on this line is causing React warnings when component is re-rendered before the promise is resolved. I suggest to use basic mount check before updating state there - 

https://github.com/contentful/field-editors/blob/master/packages/rich-text/src/Toolbar/index.js#L74

```
VM191 src.f69400ca.js:3977 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Toolbar (created by ConnectedRichTextEditor)
    in div (created by StickyToolbarWrapper)
    in StickyToolbarWrapper (created by ConnectedRichTextEditor)
    in div (created by ConnectedRichTextEditor)
    in ConnectedRichTextEditor (created by FieldConnector)
    in FieldConnector (created by RichTextEditor)
    in useEntitiesStore.Provider (created by RichTextEditor)
```

**Comment by giotiskl** [comment]
Fixed with #463. Thanks for the report.

**Comment by voronianski** [comment]
@giotiskl same issue is observed in ReferenceEditor
![image](https://user-images.githubusercontent.com/974035/97540411-e4085300-19c3-11eb-993c-c00d5aa27ec4.png)

Stack leads here - https://github.com/contentful/field-editors/blob/master/packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx#L65

**Comment by z0al** [comment]
Thank you @voronianski for letting us know. I will investigate this and work on a fix ASAP
