### ISSUE TITLE
Multi-reference editor does not call onAction when a deleted entry is removed

### ISSUE THREAD

**Issue by SirGavin** [contentful/field-editors#470]
If a previously linked entry is deleted, and then removed from the MRE via the `MissingEntityCard` element, `onAction` is not called.

It seems that the main issue with passing the `onRemove` function defined in `FetchingWrappedEntryCard` instead of `props.onRemove()` is that two of the values passed to `onAction` are retrieved from the entry object (which doesn't exist):
`id: get(entry, 'sys.id'),
contentTypeId: get(entry, 'sys.contentType.sys.id')`

As far as I can tell, the id could be pulled from the props, `props.entryId`, which just leaves the contentTypeId. Does anyone see an issue if this was supplied as null/undefined?

As an FYI, our specific use case is that we're using the `onAction` method inside an entry editor to sync two different fields in the entry. So in the given scenario, the secondary field is left with a dead entry as it would normally be removed in the `onAction` call.

Also, I'm fairly new to contentful, so it's possibly I've missed something in my analysis :)

**Comment by suevalov** [comment]
Hi @SirGavin! Thanks for reporting the issue. #471 fixes the problem and it will released shortly.

**Comment by SirGavin** [comment]
Awesome, thanks for the quick turnaround!

Was it not possible to use `props.entryId` to pass the entry id of the deleted entry for the ID param? Being passed as null atm.
