### ISSUE TITLE
@contentful/field-editor-date@^0.8.0 not published?

### ISSUE THREAD

**Issue by SirGavin** [contentful/field-editors#472]
On running `npm install @contentful/default-field-editors` I get the error `No matching version found for @contentful/field-editor-date@^0.8.0`.

When I install @contentful/field-editor-date, the installed version is 0.7.1, so looks like the latest version wasn't properly published?

**Comment by suevalov** [comment]
Hi @SirGavin 

Looks like there was a hiccup during the automatic publishing. Fixed by manually publishing 0.8.1
