### ISSUE TITLE
Character count on the multiline long text field editor

### ISSUE THREAD

**Issue by amandahogan** [contentful/field-editors#491]
I'd like to request a feature for a character count to be included on the multiline long text field editor similar to the one on the markdown editor and short text field editor.

**Comment by suevalov** [comment]
Hi @amandahogan, thanks for the feature request. We'll put it in our backlog. If you want it to happen faster, feel free to open a PR :)

**Comment by amandahogan** [comment]
@suevalov just checking if this has already been worked on? If not I'll open a PR for it.

**Comment by suevalov** [comment]
Hi @amandahogan, this is not being worked on at the moment. Feel free to open a PR 👍🏼
