### ISSUE TITLE
entry-extension-collapsible - Duplicate plugin/reset detected

### ISSUE THREAD

**Issue by imshuffling** [contentful/field-editors#579]
Getting an error trying to run the entry-extension-collapsible extension locally. 

![image](https://user-images.githubusercontent.com/739061/106456187-17f08a00-6485-11eb-8d5d-3ea915242afb.png)

```
plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]
```

Babel related?

**Comment by chrishelgert** [comment]
Extensions are migrated to app framework, issue should no longer exists
