### ISSUE TITLE
Need help with reflecting locale settings change

### ISSUE THREAD

**Issue by Nimisoere** [contentful/field-editors#596]
I have a custom editor that contains localised fields. However changing the locale on the side bar is not being reflected in the editor. I have tried storing the selected locale in React state and changing the state with the function `editor.onLocaleSettingsChanged`. 
This still doesn't work. Any pointers will be helpful. Thanks

**Comment by anho** [comment]
Hey @Nimisoere,

it would be helpful if you provide a bit more context in how you access

**Comment by anho** [comment]
Hey @Nimisoere,

can you provide us a sample of your code to understand your setup better?

I can also recommend trying out our [Community slack](https://www.contentful.com/slack/) to find help on these and other occasions.

Cheers

**Comment by Nimisoere** [comment]
Hey @anho 

Figured this out. Was missing the `key` props. 

```
    <FieldWrapper
      key={field.getValue()}
      sdk={fieldSdk}
      name={`${fieldDetails.name} ${
        displayLocaleField ? `- ${sdk.locales.names[field.locale]}` : ""
      }`}
      getEntryURL={getEntryURL}
    >
      <BaseField key={field.getValue()} sdk={fieldSdk} widgetId={widgetId} />
    </FieldWrapper>
```
