### ISSUE TITLE
field-editor-reference react-17 dependency broken

### ISSUE THREAD

**Issue by srbagg** [contentful/field-editors#676]
On creating a new contentful app using `create-contentful-app` cli and thereafter installing `@contentful/field-editor-reference` using command `npm i @contentful/field-editor-reference` causes error during installation.

```
% npm i @contentful/field-editor-reference
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@">=16.8.0" from @contentful/field-editor-shared@0.16.0
npm ERR!   node_modules/@contentful/field-editor-shared
npm ERR!     @contentful/field-editor-shared@"^0.16.0" from @contentful/field-editor-single-line@0.14.1
npm ERR!     node_modules/@contentful/field-editor-single-line
npm ERR!       @contentful/field-editor-single-line@"^0.14.1" from the root project
npm ERR!     @contentful/field-editor-shared@"^0.16.0" from @contentful/field-editor-test-utils@0.11.1
npm ERR!     node_modules/@contentful/field-editor-test-utils
npm ERR!       @contentful/field-editor-test-utils@"^0.11.1" from the root project
npm ERR!     1 more (@contentful/field-editor-reference)
npm ERR!   peer react@">=16.8.0" from @contentful/field-editor-single-line@0.14.1
npm ERR!   node_modules/@contentful/field-editor-single-line
npm ERR!     @contentful/field-editor-single-line@"^0.14.1" from the root project
npm ERR!   13 more (@contentful/field-editor-test-utils, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-sortable-hoc@1.11.0
npm ERR! node_modules/@contentful/field-editor-reference/node_modules/react-sortable-hoc
npm ERR!   react-sortable-hoc@"^1.11.0" from @contentful/field-editor-reference@2.12.2
npm ERR!   node_modules/@contentful/field-editor-reference
npm ERR!     @contentful/field-editor-reference@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```

As per the above log, `react-sortable-hoc@1.11.0` depends on react@"^0.14.0 || ^15.0.0 || ^16.0.0" whereas `create-contentful-app` cli installs latest react using create-react-app internally.

Downgrading react version to use react@16.13.1 has 3 high severity vulnerabilities which not a good option.
Thus recommending to update the package dependency version to fix the breakage.

Steps to reproduce:
1. Create new contentful app.
`npx @contentful/create-contentful-app init my-first-app`
2. Install package `@contentful/field-editor-reference`
`npm i @contentful/field-editor-reference --save`
Error will be shown

**Comment by srbagg** [comment]
I think PR #664 might have the fix for this issue.

**Comment by suevalov** [comment]
@srbagg yep, you're right. #644 should solve the problem. I verified that the new react-sortable-hoc works as expected and merge the PR, so the new version of field-editor-reference will be released shortly

**Comment by srbagg** [comment]
Great! Thanks @suevalov 😊

**Comment by suevalov** [comment]
@srbagg it's released as  `@contentful/field-editor-reference@2.13.0`
