### ISSUE TITLE
Attempted import error: 'DefaultElement' is not exported from 'slate-react'.

### ISSUE THREAD

**Issue by nekosaur** [contentful/field-editors#731]
After updating `@contentful/field-editor-rich-text` to version `0.18.11` to fix issue #715, I am not unable to compile my project with the following error message showing up.

```
/***/node_modules/@contentful/field-editor-rich-text/dist/field-editor-rich-text.esm.js
Attempted import error: 'DefaultElement' is not exported from 'slate-react'.
```

**Comment by cribbles** [comment]
Hey @nekosaur 

Apologies - looks like this was published with the wrong `dist/`. Could you try it again with the latest version (`0.18.12`)?

**Comment by nekosaur** [comment]
I can confirm that `0.18.12` fixes the issue.
