### ISSUE TITLE
Docs: canCreateEntity and canLinkEntity should be showCreateEntityAction and showLinkEntityAction

### ISSUE THREAD

**Issue by ChloeLiang** [contentful/field-editors#741]
**Actual**

Currently the mdx docs for `MultipleMediaEditor` is like this:

```jsx
<MultipleMediaEditor
  viewType="card"
  sdk={sdk}
  isInitiallyDisabled={false}
  parameters={{
    instance: {
      canCreateEntity: true,
      canLinkEntity: true
    }
  }}
 />
```

**Expected**

I think `canCreateEntity` and `canLinkEntity` should be `showCreateEntityAction` and `showLinkEntityAction` as defined in `ReferenceEditorProps` interface.

Affected components:
- SingleMediaEditor
- MultipleMediaEditor
- SingleEntryReferenceEditor
- MultipleEntryReferenceEditor

**Comment by djagya** [comment]
Hi @ChloeLiang, thank you for noticing, you're totally right! The PR fixing it is ready now and soon will be deployed.
