### ISSUE TITLE
Typescript and Latest @contentful/field-editor-reference

### ISSUE THREAD

**Issue by brianlmacdonald** [contentful/field-editors#925]
Hi, I'm building an app extension using next js, and was having build errors I couldn't resolve at the ts level when using the latest package for `@contentful/field-editor-reference`.  

```
node_modules/@contentful/f36-components/dist/f36-components.modern.js:1
export*from"@contentful/f36-badge";export*from"@contentful/f36-icon";export*from"@contentful/f36-card";export*from"@contentful/f36-core";export*from"@contentful/f36-drag-handle";export*from"@contentful/f36-spinner";export*from"@contentful/f36-table";export*from"@contentful/f36-typography";export*from"@contentful/f36-list";export*from"@contentful/f36-note";export*from"@contentful/f36-tooltip";export*from"@contentful/f36-forms";export*from"@contentful/f36-pill";export*from"@contentful/f36-button";export*from"@contentful/f36-text-link";export*from"@contentful/f36-skeleton";export*from"@contentful/f36-accordion";export*from"@contentful/f36-tabs";export*from"@contentful/f36-copybutton";export*from"@contentful/f36-popover";export*from"@contentful/f36-menu";export*from"@contentful/f36-modal";export*from"@contentful/f36-notification";export*from"@contentful/f36-asset";export*from"@contentful/f36-autocomplete";export*from"@contentful/f36-datetime";export*from"@contentful/f36-entity-list";
^^^^^^

SyntaxError: Unexpected token 'export'
```
Tweaks to next js's ts.config didn't help.

I had to set the package version to  `^2.21.2`  which is the version used in the references example app to get it to work without doing something hacky like using next's dynamic import.

Any ideas why this is happening?

_Follow up: seems like the difference maker here is f36 vs forma-36,  where the way the forma-36 components are distributed wasn't causing any issues with typescript._

_Further follow up: the problem seems like it's in the package json for f36-components, if the exports key is changed to 
`"exports": { "import": "./dist/f36-components.modern.js", "require": "./dist/f36-components.js" },` the typescript errors go away._

**Comment by djagya** [comment]
Hey @brianlmacdonald thank you for the report! I passed this issue to the Forma team. For now you're safe to use the version 2 👍  Version 4 is just an upgrade to the new, beta version of the Forma36

**Comment by brianlmacdonald** [comment]
Ok, great! Thanks
